--CREATE THE DATABASE
CREATE DATABASE COMPANY
-- USE THE DATABASE
USE COMPANY
--CREATE TABLES
Create Table Employee (
	SSN	CHAR(9) PRIMARY KEY NOT NULL,
	FNAME VARCHAR(30) NOT NULL,
	MINIT CHAR(1),
	LNAME VARCHAR(30),
	BDATE DATE,
	ADDRESS VARCHAR(100),
	SEX CHAR(1),
	SALARY DECIMAL(10,2),
	DNO INT
);

CREATE TABLE DEPARTMENT (
	DNUM INT PRIMARY KEY,
	DNAME VARCHAR(50) UNIQUE,
	MGR_SSN CHAR(9),
	MGR_START_DATE DATE,
);

CREATE Table DEPT_LOCATIONS(
	DNUMBER INT ,
	DLOCATION VARCHAR(50) ,
	PRIMARY KEY(DNUMBER, DLOCATION),
);
CREATE TABLE PROJECT (
    Pnumber INT PRIMARY KEY,
    Pname VARCHAR(50),
    Plocation VARCHAR(50),
    Dnum INT
);
CREATE TABLE WORKS_ON (
    Essn CHAR(9),
    Pno INT,
    Hours DECIMAL(5, 2),
    PRIMARY KEY (Essn, Pno)
);
CREATE TABLE DEPENDENT (
    Essn CHAR(9),
    Dependent_name VARCHAR(50),
    Sex CHAR(1),
    Bdate DATE,
    Relationship VARCHAR(20),
    PRIMARY KEY (Essn, Dependent_name)
);
-- Add foreign keys using ALTER TABLE
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
FOREIGN KEY(DNO) REFERENCES DEPARTMENT (DNUM);

ALTER TABLE EMPLOYEE 
ADD Super_ssn CHAR; 


ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
FOREIGN KEY(SUPER_SSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_Department_Manager
FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT FK_DeptLoc_Department
FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(DNUM);

ALTER TABLE PROJECT
ADD CONSTRAINT FK_Project_Department
FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(DNUM);

ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_WorksOn_Employee
FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_WorksOn_Project
FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber);

ALTER TABLE DEPENDENT
ADD CONSTRAINT FK_Dependent_Employee
FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);
