-- CREATE DATABASE
CREATE DATABASE AIRLINE
--USE DATABASE
USE AIRLINE;
--CREATE TABLES
CREATE TABLE AIRPORT(
	AIRPORT_CODE CHAR(9) PRIMARY KEY NOT NULL,
	CITY VARCHAR(50),
	STATUE VARCHAR(50),
	AIRPORT_NAME VARCHAR(50),
	SCHEDULED_DEP_TIME TIME,
	SCHEDULED_ARR_TIME TIME,
	DEP_TIME TIME,
	ARR_TIME TIME,
);
CREATE TABLE FLIGHT_LEG(
	LEG_NO INT PRIMARY KEY NOT NULL,
	
);
CREATE TABLE AIRPLANE_TYPE(
	TYPE_NAME_AIRPLANE VARCHAR(50) PRIMARY KEY NOT NULL,
	COMPANY VARCHAR(50),
	MAX_SEAT INT,
);
CREATE TABLE AIRLINE(
	AIRLINE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TOTAL_NO_OF_SEATS INT,
);
CREATE TABLE LEG_INSTANCE (
	LEG_DATE DATE PRIMARY KEY NOT NULL,
	NO_OF_AVAIL_SEATS INT,
);
CREATE TABLE SEAT(
	SEAT_NO INT ,
	CUSTOMER_NAME VARCHAR(50),
	CPHONE CHAR(8),
	PRIMARY KEY(SEAT_NO,CUSTOMER_NAME),
);
CREATE TABLE FLIGHT(
	NUMBER_OF_FLIGHT INT PRIMARY KEY,
	AIRLINE VARCHAR(50),
	WEEKDAYS VARCHAR(50),
);
CREATE TABLE FARES(
	CODE CHAR(9) PRIMARY KEY,
	AMOUNT DECIMAL (10,2),
	RESTRICTIONS VARCHAR(50),
);
CREATE TABLE CAN_LAND(
	AIRPORT_CODE CHAR(9),
	TYPE_NAME_AIRPLANE VARCHAR(50),
	PRIMARY KEY(AIRPORT_CODE,TYPE_NAME_AIRPLANE)
);
ALTER TABLE FLIGHT_LEG
ADD AIRPORT_CODE CHAR(9);


--RELATIONSHIP MATCH FREIGN KEY 

ALTER TABLE FLIGHT_LEG
ADD CONSTRAINT ARRIVAL_AIRPORT
FOREIGN KEY (AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE);

ALTER TABLE FLIGHT_LEG
ADD CONSTRAINT DEPARTURE_AIRPORT
FOREIGN KEY (AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE);

ALTER TABLE FLIGHT_LEG
ADD NUMBER_OF_FLIGHT INT;

ALTER TABLE FLIGHT_LEG
ADD CONSTRAINT LEGES
FOREIGN KEY (NUMBER_OF_FLIGHT) REFERENCES FLIGHT(NUMBER_OF_FLIGHT);

ALTER TABLE AIRLINE
ADD TYPE_NAME_AIRPLANE VARCHAR(50);

ALTER TABLE AIRLINE
ADD CONSTRAINT FK_TYPE_NAME_AIRPLANE
FOREIGN KEY(TYPE_NAME_AIRPLANE) REFERENCES AIRPLANE_TYPE(TYPE_NAME_AIRPLANE);

ALTER TABLE LEG_INSTANCE
ADD LEG_NO INT,
AIRPORT_CODE CHAR(9),
AIRPLANE_ID INT ;

ALTER TABLE LEG_INSTANCE
DROP COLUMN AIRPLANE_ID ;

ALTER TABLE LEG_INSTANCE
ADD AIRPLANE_ID INT IDENTITY(1,1);

ALTER TABLE LEG_INSTANCE
ADD CONSTRAINT INSTANCE_OF
FOREIGN KEY(LEG_NO) REFERENCES FLIGHT_LEG(LEG_NO);

ALTER TABLE LEG_INSTANCE
ADD CONSTRAINT ARRIVES
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE);

ALTER TABLE LEG_INSTANCE
ADD CONSTRAINT DEPARTS
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE);

ALTER TABLE LEG_INSTANCE
ADD CONSTRAINT ASSIGED
FOREIGN KEY(AIRPLANE_ID) REFERENCES AIRLINE(AIRLINE_ID);

ALTER TABLE SEAT
ADD RESERVATION_DATE DATE;

ALTER TABLE SEAT
ADD CONSTRAINT RESERVATION
FOREIGN KEY(RESERVATION_DATE) REFERENCES LEG_INSTANCE(LEG_DATE);

ALTER TABLE FARES
ADD NUMBER_OF_FLIGHT INT;


ALTER TABLE FARES
ADD CONSTRAINT FK_FARES
FOREIGN KEY(NUMBER_OF_FLIGHT) REFERENCES FLIGHT(NUMBER_OF_FLIGHT);



ALTER TABLE CAN_LAND
ADD CONSTRAINT LAND 
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE);

ALTER TABLE CAN_LAND
ADD CONSTRAINT FK_AIRPLANE_TYPE 
FOREIGN KEY(TYPE_NAME_AIRPLANE ) REFERENCES AIRPLANE_TYPE(TYPE_NAME_AIRPLANE);